### ISSUE TITLE
Looks like it is Python version of tcframe?

### ISSUE THREAD

**Issue by fushar** [Juanito98/omegaUp-tcTool#1]
Hi @Juanito98,

I came across this repository. Just wondering, is this literally a Python rewrite of https://github.com/ia-toki/tcframe? (I am the author and maintainer of tcframe.)

**Comment by Juanito98** [comment]
Hi @fushar yes! Read your paper and wanted to adapt it to support our National Olympiad (also wanted to implement it with some other data structure generators for my college thesis). 
I am very sorry to publish it as it is. I am planning to give tcFrame all the credit. But for now I was just playing with Python and submitted a very simple draft.

Edit. Actually It is not going to be a literally rewrite of tcFrame. Just took the facade to generate input test cases.

**Comment by fushar** [comment]
Ah I see, sure thing! Will really appreciate the credits. Good luck for your national olympiad and the thesis 😄

**Comment by Juanito98** [comment]
Thank you very much @fushar, appreciate it. I just put credits in Readme if anyone sees it.

Please let me know if you have any concerns.

**Comment by Juanito98** [comment]
Btw, I would like you to see my data structure generators when they are done. Maybe I could integrate them to tcframe if you like it

**Comment by fushar** [comment]
> Thank you very much @fushar, appreciate it. I just put credits in Readme if anyone sees it.
> 
> Please let me know if you have any concerns.

Yup, that's OK. Thank you!

**Comment by fushar** [comment]
> Btw, I would like you to see my data structure generators when they are done. Maybe I could integrate them to tcframe if you like it

Ah, actually, we already tried a "tcframe-compatible" data structure generators, here: https://github.com/afaji/tcrand. It's not actively maintained, though due to lack of time commitment 😄 maybe you want to take a look for inspiration.
